version: "3.7"
services:

  books-ms:
    build:
      context: ./book
      args:
        MVN_ARGS: -DskipTests=true
    container_name: book-ms
    ports:
      - "8102:8102"
    depends_on:
      - mongodb_db
      
  customer-ms:
    build:
      context: ./customer
      args:
        MVN_ARGS: -DskipTests=true
    container_name: customer-ms
    ports:
      - "8103:8103"
    depends_on:
      - postgres_db
  
  mongodb_db:
    image: mongo:latest
    container_name: book-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: book_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      
  postgres_db:
    image: postgres:latest
    container_name: customer-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./customer/dbinit1.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
      

volumes:
  mongodb_data: {}
  postgres_data: {}
