---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrowing-deployment
  namespace: borrowing-notification
  labels:
    app: borrowing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrowing
  template:
    metadata:
      labels:
        app: borrowing
    spec:
      containers:
        - name: borrowing-ms
          image: gaianpixel/borrowing:1.0-SNAPSHOT
          ports:
          - containerPort: 8102
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: borrowing-conf
      volumes:
      - name: borrowing-conf
        configMap:
          name: borrowing-conf
          items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: borrowing-service
  labels:
    app: borrowing
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32104
      port: 8102
      targetPort: 8102
  selector:
    app: borrowing
---
apiVersion: v1
kind: ConfigMap
data:
  application.properties: |-
   #Local MongoDB config
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=root
    spring.data.mongodb.password=root
    spring.data.mongodb.database=borrowing_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=borrowing-mongodb

    # App config
    server.port=8102
    spring.application.name=BorrowingMicroservice
    server.servlet.context-path=/borrowings-service

    # Log config
    logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

    # Management config
    management.endpoint.info.enabled=true
    management.security.enabled=false
    
    # Kafka
    kafka.sms.topic=sms
    kafka.sms.message=A new borrowing has started!
    spring.kafka.producer.bootstrap-servers=kafka:9092
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
    #spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
metadata:
  name: borrowing-conf
  namespace: borrowing-notification

  
  
