---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-ms
          image: gaianpixel/notification:1.0-SNAPSHOT
          ports:
          - containerPort: 8102
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: notification-conf
      volumes:
      - name: notification-conf
        configMap:
          name: notification-conf
          items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32105
      port: 8102
      targetPort: 8102
  selector:
    app: notification
---
apiVersion: v1
kind: ConfigMap
data:
  application.properties: |-
    # App config
    server.port=8102
    spring.application.name=BorrowingMicroservice
    server.servlet.context-path=/borrowings-service

    # Log config
    logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

    # Management config
    management.endpoint.info.enabled=true
    management.security.enabled=false
    
    # Kafka
    kafka.sms.topic=sms
    kafka.broker.urls=kafka:9092
metadata:
  name: notification-conf
  namespace: default
  
  
