version: "3.7"
services:

  customer-ms:
    build:
      context: .
      args:
        MVN_ARGS: -DskipTests=true
    container_name: customer-ms
    ports:
      - "8103:8103"
    depends_on:
      - mariadb_db

  mariadb_db:
    image: mariadb:latest
    container_name: customer-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./customer/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
      MYSQL_USER: root
      MYSQL_PASSWORD: root


volumes:
  mariadb_data: {}
